CREATE TABLE CATEGORIAS(
    CAT_CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
    CAT_UUID VARCHAR(36) DEFAULT (UUID()),
    CAT_NOME varchar(100) NOT NULL,
    CAT_DESCRICAO text,
    CAT_CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    CAT_UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY(CAT_UUID),
    UNIQUE KEY(CAT_NOME)
);