CREATE TABLE CATEGORIAS(
    CAT_CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
    CAT_UUID VARCHAR(36) DEFAULT (UUID()),
    CAT_NOME varchar(100) NOT NULL,
    CAT_DESCRICAO text,
    CAT_CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    CAT_UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY(CAT_UUID),
    UNIQUE KEY(CAT_NOME)
);
CREATE TABLE CARTEIRA(
    CAR_CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
    CAR_UUID VARCHAR(36) DEFAULT (UUID()),
    CAR_NOME varchar(100) NOT NULL,
    CAR_DESCRICAO text,
    CAR_CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    CAR_UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY(CAR_UUID),
    UNIQUE KEY(CAR_NOME)
);